
package com.cnct.wsdemo;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "modelService", targetNamespace = "http://wsdemo.cnct.com", wsdlLocation = "http://192.168.90.40:8092/whale/services/wstest?wsdl")
public class ModelService
    extends Service
{

    private final static URL MODELSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.cnct.wsdemo.ModelService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.cnct.wsdemo.ModelService.class.getResource(".");
            url = new URL(baseUrl, "http://192.168.90.40:8092/whale/services/wstest?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.90.40:8092/whale/services/wstest?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MODELSERVICE_WSDL_LOCATION = url;
    }

    public ModelService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ModelService() {
        super(MODELSERVICE_WSDL_LOCATION, new QName("http://wsdemo.cnct.com", "modelService"));
    }

    /**
     * 
     * @return
     *     returns AppService
     */
    @WebEndpoint(name = "AppServiceImpPort")
    public AppService getAppServiceImpPort() {
        return super.getPort(new QName("http://wsdemo.cnct.com", "AppServiceImpPort"), AppService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AppService
     */
    @WebEndpoint(name = "AppServiceImpPort")
    public AppService getAppServiceImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsdemo.cnct.com", "AppServiceImpPort"), AppService.class, features);
    }

}
